//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandlingExtinguishers.Core.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HandlingExtinguisherResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public HandlingExtinguisherResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandlingExtinguishers.Core.Localization.HandlingExtinguisherResources", typeof(HandlingExtinguisherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La cuenta está bloqueada..
        /// </summary>
        public static string AccountBlocked
        {
            get
            {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autenticación inválida..
        /// </summary>
        public static string InvalidAuthentication
        {
            get
            {
                return ResourceManager.GetString("InvalidAuthentication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe..
        /// </summary>
        public static string UserNotFound
        {
            get
            {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        public static string InvalidToken
        {
            get
            {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }

        public static string CompanyNotFound
        {
            get
            {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }

        public static string DuplicatedCompany
        {
            get
            {
                return ResourceManager.GetString("DuplicatedCompany", resourceCulture);
            }
        }

        public static string CreditNotFound
        {
            get
            {
                return ResourceManager.GetString("CreditNotFound", resourceCulture);
            }
        }

        public static string RelatedCredit
        {
            get
            {
                return ResourceManager.GetString("RelatedCredit", resourceCulture);
            }
        }

        public static string EmployeeNotFound
        {
            get
            {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }

        public static string ServiceNotFound
        {
            get
            {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }

        public static string RelatedService
        {
            get
            {
                return ResourceManager.GetString("RelatedService", resourceCulture);
            }
        }

        public static string WeightNotFound
        {
            get
            {
                return ResourceManager.GetString("WeightNotFound", resourceCulture);
            }
        }

        public static string RelatedWeight
        {
            get
            {
                return ResourceManager.GetString("RelatedWeight", resourceCulture);
            }
        }

        public static string ClientNotFound
        {
            get
            {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }

        public static string RelatedClient
        {
            get
            {
                return ResourceManager.GetString("RelatedClient", resourceCulture);
            }
        }

        public static string DetailExtinguisherClientNotFound
        {
            get
            {
                return ResourceManager.GetString("DetailExtinguisherClientNotFound", resourceCulture);
            }
        }

        public static string RelatedDetailExtinguisherClient
        {
            get
            {
                return ResourceManager.GetString("RelatedDetailExtinguisherClient", resourceCulture);
            }
        }

        public static string DetailServiceNotFound
        {
            get
            {
                return ResourceManager.GetString("DetailServiceNotFound", resourceCulture);
            }
        }

        public static string RelatedDetailService
        {
            get
            {
                return ResourceManager.GetString("RelatedDetailService", resourceCulture);
            }
        }

        public static string ExpenseNotFound
        {
            get
            {
                return ResourceManager.GetString("ExpenseNotFound", resourceCulture);
            }
        }

        public static string InventoryNotFound
        {
            get
            {
                return ResourceManager.GetString("InventoryNotFound", resourceCulture);
            }
        }

        public static string RelatedInventory
        {
            get
            {
                return ResourceManager.GetString("RelatedInventory", resourceCulture);
            }
        }

        public static string PriceNotFound
        {
            get
            {
                return ResourceManager.GetString("PriceNotFound", resourceCulture);
            }
        }

        public static string RelatedPrice
        {
            get
            {
                return ResourceManager.GetString("RelatedPrice", resourceCulture);
            }
        }

        public static string ProductNotFound
        {
            get
            {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }

        public static string RelatedProduct
        {
            get
            {
                return ResourceManager.GetString("RelatedProduct", resourceCulture);
            }
        }

        public static string TypeExtinguisherNotFound
        {
            get
            {
                return ResourceManager.GetString("TypeExtinguisherNotFound", resourceCulture);
            }
        }

        public static string TypeExtinguisherRelated { 
            get
            {
                return ResourceManager.GetString("TypeExtinguisherRelated", resourceCulture);
            }
        }
    }
}
